# Copyright 2025 Huawei Technologies Co., Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============================================================================

all:
  vars:
    ansible_user: root
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o IdentitiesOnly=yes'
    ansible_ssh_private_key_file:  ~/.ssh/id_rsa  # Private key path on the executor
    global_port_base: 11000
    base_api_port: 13000
    proxy_port: 7000
    port_offset:
      P: 0      # Actual port range for group P: 8000-8099
      D: 200    # Actual port range for group D: 8200-8299

  children:
    P:
      hosts:
        p0:
          ansible_host: "127.0.0.1"
          node_rank: 0
          kv_rank: 0
          node_port: "{{ global_port_base + port_offset.P + kv_rank }}"
          api_port: "{{ base_api_port + port_offset.P + kv_rank }}"
          host_ip: "127.0.0.1"
          ascend_rt_visible_devices: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"

        p1:
          ansible_host: "127.0.0.2"
          node_rank: 0
          kv_rank: 1
          node_port: "{{ global_port_base + port_offset.P + kv_rank }}"
          api_port: "{{ base_api_port + port_offset.P + kv_rank }}"
          host_ip: "127.0.0.2"
          ascend_rt_visible_devices: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"
        
        p2:
          ansible_host: "127.0.0.3"
          node_rank: 0
          kv_rank: 2
          node_port: "{{ global_port_base + port_offset.P + kv_rank }}"
          api_port: "{{ base_api_port + port_offset.P + kv_rank }}"
          host_ip: "127.0.0.3"
          ascend_rt_visible_devices: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"

        p3:
          ansible_host: "127.0.0.4"
          node_rank: 0
          kv_rank: 3
          node_port: "{{ global_port_base + port_offset.P + kv_rank }}"
          api_port: "{{ base_api_port + port_offset.P + kv_rank }}"
          host_ip: "127.0.0.4"
          ascend_rt_visible_devices: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"

        p4:
          ansible_host: "127.0.0.5"
          node_rank: 0
          kv_rank: 4
          node_port: "{{ global_port_base + port_offset.P + kv_rank }}"
          api_port: "{{ base_api_port + port_offset.P + kv_rank }}"
          host_ip: "127.0.0.5"
          ascend_rt_visible_devices: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"

        p5:
          ansible_host: "127.0.0.6"
          node_rank: 0
          kv_rank: 5
          node_port: "{{ global_port_base + port_offset.P + kv_rank }}"
          api_port: "{{ base_api_port + port_offset.P + kv_rank }}"
          host_ip: "127.0.0.6"
          ascend_rt_visible_devices: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"

        p6:
          ansible_host: "127.0.0.7"
          node_rank: 0
          kv_rank: 6
          node_port: "{{ global_port_base + port_offset.P + kv_rank }}"
          api_port: "{{ base_api_port + port_offset.P + kv_rank }}"
          host_ip: "127.0.0.7"
          ascend_rt_visible_devices: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"

        p7:
          ansible_host: "127.0.0.8"
          node_rank: 0
          kv_rank: 7
          node_port: "{{ global_port_base + port_offset.P + kv_rank }}"
          api_port: "{{ base_api_port + port_offset.P + kv_rank }}"
          host_ip: "127.0.0.8"
          ascend_rt_visible_devices: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"
    
    D:
      hosts:
        d0:
          ansible_host: "127.0.0.9"
          node_rank: 0
          node_port: "{{ global_port_base + port_offset.D }}"
          api_port: "{{ base_api_port + port_offset.D + node_rank }}"
          host_ip: "127.0.0.9"
          ascend_rt_visible_devices: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"

        d1:
          ansible_host: "127.0.0.10"
          node_rank: 1
          node_port: "{{ global_port_base + port_offset.D }}"
          api_port: "{{ base_api_port + port_offset.D + node_rank }}"
          host_ip: "127.0.0.9"
          ascend_rt_visible_devices: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"

        d2:
          ansible_host: "127.0.0.11"
          node_rank: 2
          node_port: "{{ global_port_base + port_offset.D }}"
          api_port: "{{ base_api_port + port_offset.D + node_rank }}"
          host_ip: "127.0.0.9"
          ascend_rt_visible_devices: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"

        d3:
          ansible_host: "127.0.0.12"
          node_rank: 3
          node_port: "{{ global_port_base + port_offset.D }}"
          api_port: "{{ base_api_port + port_offset.D + node_rank }}"
          host_ip: "127.0.0.9"
          ascend_rt_visible_devices: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"

        d4:
          ansible_host: "127.0.0.13"
          node_rank: 4
          node_port: "{{ global_port_base + port_offset.D }}"
          api_port: "{{ base_api_port + port_offset.D + node_rank }}"
          host_ip: "127.0.0.9"
          ascend_rt_visible_devices: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"

        d5:
          ansible_host: "127.0.0.14"
          node_rank: 5
          node_port: "{{ global_port_base + port_offset.D }}"
          api_port: "{{ base_api_port + port_offset.D + node_rank }}"
          host_ip: "127.0.0.9"
          ascend_rt_visible_devices: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"

        d6:
          ansible_host: "127.0.0.15"
          node_rank: 6
          node_port: "{{ global_port_base + port_offset.D }}"
          api_port: "{{ base_api_port + port_offset.D + node_rank }}"
          host_ip: "127.0.0.9"
          ascend_rt_visible_devices: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"

        d7:
          ansible_host: "127.0.0.16"
          node_rank: 7
          node_port: "{{ global_port_base + port_offset.D }}"
          api_port: "{{ base_api_port + port_offset.D + node_rank }}"
          host_ip: "127.0.0.9"
          ascend_rt_visible_devices: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"

        d8:
          ansible_host: "127.0.0.17"
          node_rank: 8
          node_port: "{{ global_port_base + port_offset.D }}"
          api_port: "{{ base_api_port + port_offset.D + node_rank }}"
          host_ip: "127.0.0.9"
          ascend_rt_visible_devices: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"

        d9:
          ansible_host: "127.0.0.18"
          node_rank: 9
          node_port: "{{ global_port_base + port_offset.D }}"
          api_port: "{{ base_api_port + port_offset.D + node_rank }}"
          host_ip: "127.0.0.9"
          ascend_rt_visible_devices: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"

        d10:
          ansible_host: "127.0.0.19"
          node_rank: 10
          node_port: "{{ global_port_base + port_offset.D }}"
          api_port: "{{ base_api_port + port_offset.D + node_rank }}"
          host_ip: "127.0.0.9"
          ascend_rt_visible_devices: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"

        d11:
          ansible_host: "127.0.0.20"
          node_rank: 11
          node_port: "{{ global_port_base + port_offset.D }}"
          api_port: "{{ base_api_port + port_offset.D + node_rank }}"
          host_ip: "127.0.0.9"
          ascend_rt_visible_devices: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"

        d12:
          ansible_host: "127.0.0.21"
          node_rank: 12
          node_port: "{{ global_port_base + port_offset.D }}"
          api_port: "{{ base_api_port + port_offset.D + node_rank }}"
          host_ip: "127.0.0.9"
          ascend_rt_visible_devices: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"

        d13:
          ansible_host: "127.0.0.22"
          node_rank: 13
          node_port: "{{ global_port_base + port_offset.D }}"
          api_port: "{{ base_api_port + port_offset.D + node_rank }}"
          host_ip: "127.0.0.9"
          ascend_rt_visible_devices: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"

        d14:
          ansible_host: "127.0.0.23"
          node_rank: 14
          node_port: "{{ global_port_base + port_offset.D }}"
          api_port: "{{ base_api_port + port_offset.D + node_rank }}"
          host_ip: "127.0.0.9"
          ascend_rt_visible_devices: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"

        d15:
          ansible_host: "127.0.0.24"
          node_rank: 15
          node_port: "{{ global_port_base + port_offset.D }}"
          api_port: "{{ base_api_port + port_offset.D + node_rank }}"
          host_ip: "127.0.0.9"
          ascend_rt_visible_devices: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"

        d16:
          ansible_host: "127.0.0.25"
          node_rank: 16
          node_port: "{{ global_port_base + port_offset.D }}"
          api_port: "{{ base_api_port + port_offset.D + node_rank }}"
          host_ip: "127.0.0.9"
          ascend_rt_visible_devices: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"

        d17:
          ansible_host: "127.0.0.26"
          node_rank: 17
          node_port: "{{ global_port_base + port_offset.D }}"
          api_port: "{{ base_api_port + port_offset.D + node_rank }}"
          host_ip: "127.0.0.9"
          ascend_rt_visible_devices: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"
        
    C:
      hosts:
        c0:
          ansible_host: "127.0.0.1"
          node_rank: 0
          node_port: "{{ proxy_port + node_rank }}"
          role: "C"
